spring:
  config:
    import: optional:file:./.env.production[.properties],optional:file:./api-gateway/.env.production[.properties]
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: identity-service
              uri: ${IDENTITY_SERVICE_URL}
              predicates:
                - Path=/api/auth/**

app:
  security:
    jwt:
      secret: ${JWT_SECRET}