-- Baseline schema for notification-service.
--
-- Two tables, and neither of them is a copy of anything upstream: this service
-- holds the wording it sends and the record of what it was told, and asks
-- identity-service for the rest at the moment it needs it -- which is to say,
-- never, because the event carries it.
--
-- Written to match what Hibernate expects, since ddl-auto: validate checks the
-- entities against this on every start. Anything the entities need from here
-- on is a new V-numbered migration, not an edit to this file.

-- Subject and body of an outgoing email, rendered by TemplateRenderer.
CREATE TABLE notification_template (
    template_id bigint GENERATED BY DEFAULT AS IDENTITY,
    -- What a handler asks for, e.g. 'user.welcome'. Unique, so the lookup by key
    -- can never be ambiguous.
    template_key varchar(255) NOT NULL,
    -- Also rendered: a subject line wants the recipient's name as much as the
    -- body does.
    subject varchar(255) NOT NULL,
    -- text, not varchar(n): an email body has no natural length limit.
    body text NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (template_id)
);

ALTER TABLE notification_template
    ADD CONSTRAINT uk_notification_template_key UNIQUE (template_key);

-- Every envelope that reached notification.q, recorded before anything acted on
-- it. The queue is bound to '#', so this is a log of the whole event stream as
-- this service saw it, not only of the events it sends mail for.
CREATE TABLE audit_log (
    -- The event id from the envelope, used as the key rather than a surrogate:
    -- one event is one row, and the primary key is what enforces that if the
    -- idempotent-consumer claim ever fails to.
    event_id uuid NOT NULL,
    type varchar(255) NOT NULL,
    correlation_id varchar(255),
    payload jsonb NOT NULL,
    -- When this service took delivery. The envelope's own occurredAt says when
    -- the thing happened upstream; the gap between them is the pipeline's lag.
    received_at timestamp(6) with time zone NOT NULL,
    PRIMARY KEY (event_id)
);

-- Supports the two questions this table gets asked: what happened to one
-- request, and what has arrived lately.
CREATE INDEX idx_audit_log_correlation_id ON audit_log (correlation_id);
CREATE INDEX idx_audit_log_received_at ON audit_log (received_at DESC);
