-- Baseline schema for identity-service.
--
-- Transcribed verbatim from the DDL Hibernate emitted with ddl-auto: update
-- against an empty identity_db, so that ddl-auto: validate passes against it
-- unchanged. Column order, types, nullability and the generated constraint
-- names are all Hibernate's -- do not tidy them up. Anything the entities
-- need from here on is a new V-numbered migration, not an edit to this file.

CREATE TABLE departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) NOT NULL,
    department_name varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (department_id)
);

CREATE TABLE roles (
    role_id bigint GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NOT NULL,
    -- Hibernate derives this check from @Enumerated(STRING) on Role. Adding a
    -- constant to the enum means altering it here.
    role_name varchar(255) NOT NULL CHECK ((role_name IN ('SYSTEM_ADMIN','DEPARTMENT_HEAD','HR_MANAGER','FINANCE_MANAGER','EMPLOYEE','USER'))),
    PRIMARY KEY (role_id)
);

CREATE TABLE user_roles (
    role_id bigint NOT NULL,
    user_id bigint NOT NULL,
    assigned_at timestamp(6) NOT NULL,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users (
    user_id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) NOT NULL,
    email varchar(255) NOT NULL,
    is_assigned boolean NOT NULL,
    is_banned boolean NOT NULL,
    password varchar(255) NOT NULL,
    username varchar(255) NOT NULL,
    department_id bigint,
    PRIMARY KEY (user_id)
);

ALTER TABLE departments
    ADD CONSTRAINT ukqyf2ekbfpnddm6f3rkgt39i9o UNIQUE (department_name);

ALTER TABLE roles
    ADD CONSTRAINT uk716hgxp60ym1lifrdgp67xt5k UNIQUE (role_name);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6
    FOREIGN KEY (role_id) REFERENCES roles (role_id);

ALTER TABLE user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f
    FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE users
    ADD CONSTRAINT fksbg59w8q63i0oo53rlgvlcnjq
    FOREIGN KEY (department_id) REFERENCES departments (department_id);
