CREATE TABLE departments (
    department_id bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) NOT NULL,
    department_name varchar(255) NOT NULL,
    description varchar(255),
    PRIMARY KEY (department_id)
);

ALTER TABLE departments
    ADD CONSTRAINT uk_org_departments_name UNIQUE (department_name);
