CREATE TABLE designations (
    designation_id bigint GENERATED BY DEFAULT AS IDENTITY,
    name varchar(100) NOT NULL,
    department_id bigint NOT NULL,
    description varchar(500),
    created_at timestamp(6) NOT NULL,
    PRIMARY KEY (designation_id),
    CONSTRAINT fk_designations_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT uk_designations_department_name UNIQUE (department_id, name)
);

CREATE INDEX idx_designations_department_id ON designations (department_id);
